### ISSUE TITLE
使用menu组件时设置mode="vertical"的方式，结果子菜单弹窗没有显示出来，大佬们帮忙看下

### ISSUE THREAD

**Issue by robertyclin** [vueComponent/ant-design-vue-nuxt#55]
1、下载ant-design-vue-nuxt代码，本地运行
2、复制antdv的menu例子，运行结果有warning，并且子菜单弹窗并没有显示出来。
antdv官网demo
<img width="968" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/23149335/6a709d80-18a2-4cfa-b3f2-7ffef5729905">
本地demo
<img width="626" alt="image" src="https://github.com/vueComponent/ant-design-vue-nuxt/assets/23149335/f29b33a3-411d-4bae-8aac-ec3b8a04d5bb">
报错信息如下：
[Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(v-fgt) 
- Server rendered DOM:   
  at <Trigger popupClassName="ant-menu-inline-collapsed-tooltip css-dev-only-do-not-override-3m4nqy" prefixCls="ant-tooltip" action="hover"  ... > 
  at <Tooltip title=null overlayClassName="ant-menu-inline-collapsed-tooltip css-dev-only-do-not-override-3m4nqy" trigger="hover"  ... > 
  at <ATooltip title=null open=false placement="right"  ... > 
  at <AMenuItem key="3" title="Option 3" originItemValue= {key: '3', label: 'Option 3', title: 'Option 3'} > 
  at <SubMenuList id="sub_menu_1_$$_sub1-popup" ref=Ref< undefined > > 
  at <MenuContextProvider mode="vertical" > 
  at <Align target=fn<bound getRootDomNode> key="popup" ref=Ref< undefined >  ... > 
  at <BaseTransition onBeforeEnter=fn<onBeforeEnter> appear=false persisted=false  ... > 
  at <Transition ref=Ref< undefined > onBeforeEnter=fn<onShowPrepare> > 
  at <PopupInner prefixCls="ant-menu-submenu" point=null align= {points: Array(2), overflow: {…}, offset: Array(2)}  ... > 
  at <Popup prefixCls="ant-menu-submenu" destroyPopupOnHide=false visible=true  ... > 
  at <Portal getContainer=fn<getContainer3> ref=Ref< undefined > didUpdate=fn<bound handlePortalUpdate> > 
  at <PortalWrapper key="portal" getContainer=undefined didUpdate=fn<bound handlePortalUpdate>  ... > 
  at <Trigger prefixCls="ant-menu-submenu" popupClassName="ant-menu-submenu-popup ant-menu ant-menu-light css-dev-only-do-not-override-3m4nqy" stretch=null  ... > 
  at <PopupTrigger mode="vertical" prefixCls="ant-menu-submenu" visible=true  ... > 
  at <ResizeObserver disabled=true onResize=fn<onResize> class="ant-menu-submenu ant-menu-submenu-vertical ant-menu-submenu-open ant-menu-submenu-active"  ... > 
  at <Item class="ant-menu-submenu ant-menu-submenu-vertical ant-menu-submenu-open ant-menu-submenu-active" prefixCls="ant-menu-overflow-item" responsive=false  ... > 
  at <OverflowContextProvider value=null > 
  at <RawItem component="li" role="none" class="ant-menu-submenu ant-menu-submenu-vertical ant-menu-submenu-open ant-menu-submenu-active"  ... > 
  at <MenuContextProvider mode="vertical" > 
  at <ASubMenu key="sub1" icon=fn<icon> title="Navigation Three"  ... > 
  at <OverflowContextProvider key=2 value= {prefixCls: 'ant-menu-overflow-item', responsive: false, component: {…}, invalidate: true, order: 2, …} > 
  at <ResizeObserver disabled=true onResize=fn<onOverflowResize> > 
  at <Overflow style= {width: '256px'} onMousedown=undefined prefixCls="ant-menu-overflow"  ... > 
  at <AMenu openKeys= ['sub1'] onUpdate:openKeys=fn selectedKeys= []  ... > 
  at <Anonymous value= {hashed: true, components: {…}, theme: Theme, token: {…}} > 
  at <ALocaleProvider locale=undefined ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider theme= {algorithm: ƒ} > 
  at <AStyleProvider cache= Entity {cache: Map(5), instanceId: '465803411031b5b'} > 
  at <AExtractStyle> 
  at <App key=3 > 
  at <NuxtRoot>

**Comment by luyaozi** [comment]
我也遇到了  mode="horizontal"  也不生效    nuxt官方文档 安装下来没有css   最后才发现还需要 除了 @ant-design-vue/nuxt  还需要  ant-design-vue    关键是官方文档都没有说明     就真的没见过这么垃圾的     kpi项目何必开源

**Comment by ezewu** [comment]
> 我也遇到了 mode="horizontal" 也不生效 nuxt官方文档 安装下来没有css 最后才发现还需要 除了 @ant-design-vue/nuxt 还需要 ant-design-vue 关键是官方文档都没有说明 就真的没见过这么垃圾的 kpi项目何必开源

我也碰到了这个问题 ，安装一下ant-design-vue 就可以了吗？

**Comment by ezewu** [comment]
安装了，刷新也是报错的

- rendered on server: id="rc_select_TEST_OR_SSR"
  - expected on client: id="rc_select_1"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <Anonymous type="search" id="rc_select_1" ref=fn<func>  ... > 
  at <SelectInput inputRef=fn<func> prefixCls="ant-select" id="rc_select_1"  ... > 
  at <SingleSelector choiceTransitionName="" tagRender=undefined optionLabelRender=undefined  ... > 
  at <Selector choiceTransitionName="" placement=undefined tagRender=undefined  ... > 
  at <Trigger prefixCls="ant-select-dropdown" popupElement= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} containerWidth=null  ... > 
  at <SelectTrigger ref=Ref< null > disabled=undefined prefixCls="ant-select"  ... > 
  at <BaseSelect choiceTransitionName="" placement=undefined tagRender=undefined  ... > 
  at <VcSelect ref=Ref< undefined > virtual=undefined dropdownMatchSelectWidth=undefined  ... > 
  at <ASelect value=0 style= {width: '150px'} onChange=fn > 
  at <MediaHead ref="mediaHead" type=0 sort=0  ... > 
  at <Audio onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/my/720vr/media/audio" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/my/720vr/media/audio', hash: '', query: {…}, name: 'my-720vr-media-audio', path: '/my/720vr/media/audio', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <720vr onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/my/720vr" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/my/720vr/media/audio', hash: '', query: {…}, name: 'my-720vr-media-audio', path: '/my/720vr/media/audio', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <My onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/my" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/my/720vr/media/audio', hash: '', query: {…}, name: 'my-720vr-media-audio', path: '/my/720vr/media/audio', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <AStyleProvider cache= Entity {cache: Map(11), instanceId: '53b821912514543'} > 
  at <AExtractStyle> 
  at <App key=3 > 
  at <NuxtRoot>
log @ browser.mjs?v=87798ed6:44
_log @ core.mjs?v=87798ed6:381
resolveLog @ core.mjs?v=87798ed6:349
_logFn @ core.mjs?v=87798ed6:377
（匿名） @ core.mjs?v=87798ed6:306
warn$1 @ chunk-SGQVLJ32.js?v=87798ed6:1512
propHasMismatch @ chunk-SGQVLJ32.js?v=87798ed6:6605
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6355
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateFragment @ chunk-SGQVLJ32.js?v=87798ed6:6449
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6204
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateFragment @ chunk-SGQVLJ32.js?v=87798ed6:6449
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6204
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSuspense @ chunk-SGQVLJ32.js?v=87798ed6:3165
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6274
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSuspense @ chunk-SGQVLJ32.js?v=87798ed6:3165
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6274
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateChildren @ chunk-SGQVLJ32.js?v=87798ed6:6408
hydrateElement @ chunk-SGQVLJ32.js?v=87798ed6:6314
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6219
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6238
hydrateSuspense @ chunk-SGQVLJ32.js?v=87798ed6:3165
hydrateNode @ chunk-SGQVLJ32.js?v=87798ed6:6274
hydrateSubTree @ chunk-SGQVLJ32.js?v=87798ed6:7440
componentUpdateFn @ chunk-SGQVLJ32.js?v=87798ed6:7460
run @ chunk-SGQVLJ32.js?v=87798ed6:435
instance.update @ chunk-SGQVLJ32.js?v=87798ed6:7597
setupRenderEffect @ chunk-SGQVLJ32.js?v=87798ed6:7607
mountComponent @ chunk-SGQVLJ32.js?v=87798ed6:7375
await in mountComponent（异步）
（匿名） @ entry.js:66
显示另外 201 个框架
收起

**Comment by JChehe** [comment]
> 我也遇到了 mode="horizontal" 也不生效 nuxt官方文档 安装下来没有css 最后才发现还需要 除了 @ant-design-vue/nuxt 还需要 ant-design-vue 关键是官方文档都没有说明 就真的没见过这么垃圾的 kpi项目何必开源

![1721922981255](https://github.com/user-attachments/assets/83529c76-ff62-4e7e-a9b0-4a5c72953212)
两者安装还是不行。

**Comment by wongyat88** [comment]
the problem is  'Hydration node mismatch', seem ant design is not fully support SSR. Even i try to wrap it with Client only, the dropdown is still in incorrect position.

**Comment by zhangbobo131415** [comment]
这个报错的原因是antd的一些组件在服务端渲染出来的dom和在浏览器渲染出来的dom不完全一致导致的。比如`<div>new Date().toString()</div>`这样的dom节点在服务端和客户端渲染的内容完全不一样，就会引发Hydration这样的错误。其中一种的解决办法是让这个节点只在一个设备上渲染，比如nuxt就提供了ClientOnly组件
<img width="693" alt="image" src="https://github.com/user-attachments/assets/1e942c37-a357-4228-8320-b929e6f82ae0">
其他的ssr框架应该也有类似的组件，对应修改就行
@JChehe @ezewu @robertyclin @aibayanyu20 @
